[package]
name = "quoridor_viewer"
version = "0.1.0"
authors = ["Terasaki Shun <t.tera1217@gmail.com>"]

[dependencies]
rocket = "*"
rocket_codegen ="*"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates", "tera_templates"]
